print('================================================================')
print('|                                                               |')
print('|                 🔍 4. Maior e Menor Número                    |')
print('|                                                               |')
print('================================================================')
n1 = int(input(" Digite o primeiro numero: "))
n2 = int(input(" Digite o segundo numero: "))
n3 = int(input(" Digite o terceiro numero: "))

maior = max(n1,n2,n3)
print("O maior numero e: ",maior)
menor = min(n1,n2,n3)
print("O menor numero e: ",menor)